FROM node:20-alpine AS build
WORKDIR /app
RUN apk add --no-cache gettext
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build


# production stage
FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache gettext
RUN npm install -g serve
COPY --from=build /app/build ./build/
COPY public/env.template.js ./build/public/env.template.js
CMD sh -c "envsubst < /app/build/public/env.template.js > /app/build/public/env.js && serve -s build -l ${PORT}"
EXPOSE 8080