FROM node:20-alpine
RUN apk add --no-cache gettext
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
#CMD ["npm", "run", "dev", "--", "--host"]

CMD sh -c "envsubst < public/env.template.js > public/env.js && npm run start -- --host" 