FROM node:20-alpine AS build
WORKDIR /app
RUN apk add --no-cache gettext
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build


# production stage
FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache gettext
RUN npm install -g serve
COPY --from=build /app/build ./dist/
COPY public/env.template.js ./dist/env.template.js
CMD sh -c "envsubst < /dist/env.template.js > /dist/env.js && serve -s dist -l 80"
EXPOSE 80