#install dependencies
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

#runtime image
FROM node:18-alpine
WORKDIR /app

RUN npm install knex -g

#copy needed files
COPY --from=build /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production

#run as non-root user
USER node

EXPOSE 8080
CMD sh -c "knex migrate:latest && knex seed:run && node index.js"