name: Docker Compose CI
on: [push]
jobs:
    Test-Run:
        runs-on: ubuntu-latest
        services:
            db:
                image: postgres:17
                env:
                    POSTGRES_DB: testdb
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                ports:
                    - "5432:5432"
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            -   name: Checkout code
                uses: [actions/checkout@v5](https://github.com)
            -   name: Build and run Docker Compose stack
                run: docker compose up -d --build
            -   name: Check running containers
                run: docker ps
            -   name: wait for database to be healthy
                run: sleep 10
            -   name: Run application test
                run: docker compose exec web npm test
                run: docker compose exec api node index.js
            -   name: Clean up containers
                if: always()
                run: docker compose down